version: "3.8"

services:
  db:
    image: postgres:15
    container_name: onespace_postgres
    volumes:
      - ./db/db:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
    env_file:
      - .env
    networks:
      - onespace_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: onespace_pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: onespace@onespace.com
      PGADMIN_DEFAULT_PASSWORD: onespace
    volumes:
      - ./db/db:/var/lib/postgresql/data
    links:
      - db
    networks:
      - onespace_network

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - '8000:8000'
    expose:
      - 8000
    depends_on:
      - db
      - pgadmin
    restart: always
    networks:
      - onespace_network

networks:
  onespace_network:
    external: true
